/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'R',
      link: {
        type: 'generated-index',
        title: 'R',
        description: '数据分析和数据可视化',
      },
      items: [
        'R/R',
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      link: {
        type: 'generated-index',
        title: 'JavaScript',
        description: 'JavaScript 高级程序设计(第四版) 读书笔记',
      },
      items: [
        'JavaScript/JavaScript-basic',
        'JavaScript/JavaScript-advanced'
      ],
    },
    {
      type: 'category',
      label: 'React',
      link: {
        type: 'generated-index',
        title: 'React',
        description: 'React 18 学习笔记'
      },
      items: [
        'React/React-basic',
      ],
    }
  ],
}

module.exports = sidebars
